version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: sttproj
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres-data:
